### ISSUE TITLE
Builds continue after solver failures

### ISSUE THREAD

**Issue by chrisburr** [TheSnakePit/boa#2]
When the solver fails a message is printed like below however the build continues regardless:

```
MAMBA failed to solve specs

, _spcs,

for channels

%s

The reported errors are:

 ['local', 'conda-forge', 'defaults'] Encountered problems while solving.
Problem: package davix-0.6.7-hfd78c64_0 requires libxml2 >=2.9.8,<2.10.0a0, but none of the providers can be installed
```

**Comment by wolfv** [comment]
yep, I noticed that too :) will fix it today

**Comment by wolfv** [comment]
raising a real RuntimeError now: https://github.com/TheSnakePit/boa/blob/6be7d4c7ef19e67a1e7aae2cf48be6a5280d0f8f/boa/cli/build.py#L191

with some nicely formatted error output.

Thanks for testing!

**Comment by chrisburr** [comment]
I think this has now broken builds with multiple outputs as it now errors saying the yet-to-be-built output doesn't exist.

(The fix in #3 seems to have worked 👍)

**Comment by wolfv** [comment]
you're saying that master has another bug with multiple builds or that this broke a specific build for you because it's not continuing anymore?
Not completely getting that statement, sorry! 

I tested builds with multiple outputs yesterday and it should be mostly fine... let me check again.

**Comment by chrisburr** [comment]
Sorry, my fault for being excessively brief! I was building something like:
```yaml
outputs:
  - name: A
  - name: B
    requirements:
        run:
            - A
  - name: C
    requirements:
        run:
            - A
            - B
  - name: D
    requirements:
        run:
            - A
            - B
            - C
```
which resulted in an error saying that A, B and C don't exist. Reverting 6be7d4c7ef19e67a1e7aae2cf48be6a5280d0f8f fixed the problem. I can make a reproducer recipe later today.
